"""Generate Apache 2.4 configuration from the synced lists.

claims_log_conf: an additive GlobalLog that records only requests whose user-agent claims a crawler, with the
    vhost and the Cloudflare client header. It changes no existing log and no application behaviour.
enforce_conf: an authz block that denies a claimed crawler whose client IP is outside the allowed set of its
    list (current version plus every version in force within the tolerance window). AuthMerging And keeps every
    stricter rule a vhost already has, such as a <Files> deny on .env.
"""
from .vendors import CLASS_LIST, UA_CLASSES


def _ua_regex():
    return "(" + "|".join(token.decode() for token, _ in UA_CLASSES) + ")"


def claims_log_conf(log_path):
    return f"""# Generated by aiverify. Logs only requests whose user-agent claims a known crawler.
SetEnvIfNoCase User-Agent "{_ua_regex()}" aiv_claim
GlobalLog "{log_path}" "%{{sec}}t %v %a \\"%{{CF-Connecting-IP}}i\\" \\"%r\\" %>s %B \\"%{{Referer}}i\\" \\"%{{User-Agent}}i\\"" env=aiv_claim
"""


def enforce_conf(verifiers, today, tolerance, deny_unverifiable=False, stamp="", gate="if", exempt=()):
    """verifiers: {list name: VersionedList}. Returns the config text and per-class prefix counts.

    gate="if" wraps the rules in <If "-n reqenv('aiv_cls')">, so a request that claims no crawler never merges
    the authz tree. gate="location" applies the block to every request. The bench found no significant latency
    difference between the two for requests that claim no crawler; both pass the same functional tests.
    exempt: CIDRs always allowed, e.g. Cloudflare's, on a vhost where the real client IP is not restored."""
    lines = [f"# Generated by aiverify {stamp}. Do not edit; rerun sync.", "<IfModule mod_setenvif.c>"]
    # SetEnvIf runs in order and the last match wins, so emit the generic tokens first.
    for token, cls in reversed(UA_CLASSES):
        lines.append(f'    SetEnvIfNoCase User-Agent "{token.decode()}" aiv_cls={cls}')
    opener = "<If \"-n reqenv('aiv_cls')\">" if gate == "if" else '<Location "/">'
    lines += ["</IfModule>", opener, "    AuthMerging And", "    <RequireAll>", "        Require all granted"]
    counts = {}
    for _, cls in UA_CLASSES:
        name = CLASS_LIST.get(cls)
        if name is None or name not in verifiers:
            if deny_unverifiable:
                lines.append(f"        Require expr \"reqenv('aiv_cls') != '{cls}'\"")
            continue
        allowed = verifiers[name].allowed_prefixes(today, tolerance.get(name, 0))
        counts[cls] = len(allowed)
        lines.append("        <RequireAny>")
        lines.append(f"            Require expr \"reqenv('aiv_cls') != '{cls}'\"")
        for i in range(0, len(allowed), 50):
            lines.append("            Require ip " + " ".join(allowed[i:i + 50]))
        if exempt:
            lines.append("            Require ip " + " ".join(exempt))
        lines.append("        </RequireAny>")
    lines += ["    </RequireAll>", "</If>" if gate == "if" else "</Location>", ""]
    return "\n".join(lines), counts
